name = "MotionCorrespondence"
uuid = "e0294b02-1e2f-49e8-b79a-9fa80cb60cda"
authors = ["Andrew Hynes <andrewjhynes@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
